using System.Text;

namespace MycoKeyCreator.Library.SqlQueryBuilders
{
    public class PostgreSQLQueryBuilder : SQLQueryBuilder
    {
        public override string CreateDatabase(string folder, string dbName)
        {
            return @"CREATE DATABASE " + dbName + @" WITH OWNER = postgres ENCODING = 'UTF8' CONNECTION LIMIT = -1;";
        }

        public override void AppendIdentityColumn(StringBuilder stringBuilder, string columnName)
        {
            stringBuilder.Append(columnName);
            stringBuilder.Append(" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
        }
    }
}
